; PlatformIO Project Configuration Files

[env]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    bogde/HX711 @ ^0.7.5

; ENVIRONMENT 1: THE TRANSMITTER NODE (EDGE COMPUTE)
[env:transmitter_node]
; Compile everything EXCEPT the server code
build_src_filter = +<*> -<main_server.cpp>
build_flags = 
    -D IS_NODE=1

; ENVIRONMENT 2: THE RECEIVER SERVER (GATEWAY)
[env:receiver_server]
; Compile everything EXCEPT the node code and the filter math
build_src_filter = +<*> -<main_node.cpp> -<cii_filter.cpp>
build_flags = 
    -D IS_SERVER=1